### ISSUE TITLE
wake doesn't work

### ISSUE THREAD

**Issue by vinceoralim** [syscl/Fix-usb-sleep#2]
Hello,

on my setup (mbp 2012, osx 10.11.5), what works:
- sleep : I don't have the "Disk not ejected properly" anymore
- fixUSB.sh seem to be registered, but I can't see the deamon with `launchctl list`

what doesn't work:
- wake : usb drive is missing, but I can easily mount it with `diskutil mount`

note : the whole thing worked on the first day I ran it, but not anymore (after shutdown). I re-launched the script, though.

thks

**Comment by syscl** [comment]
Hi @vinceralim,

Can you post your diskutil list with plug-in USB (before sleep & after sleep)?

Thx!
syscl

**Comment by vinceoralim** [comment]
you're fast !
no differences before and after :
```
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *480.1 GB   disk0
   1:                        EFI EFI                     209.7 MB   disk0s1
   2:                  Apple_HFS Macbook                 479.2 GB   disk0s2
   3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
/dev/disk1 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *1.0 TB     disk1
   1:               Windows_NTFS Extension               1.0 TB     disk1s1
```
note : Extension is not actually a NTFS as reported, but a exFat format

**Comment by syscl** [comment]
Lol, 

I will try to fix it now(add mount function at startup).

BTW, which mount command do you use?

**Comment by vinceoralim** [comment]
`diskutil mount disk1s1` (also doable with the disk utility app)
Previously, before using your script, I had a timeout error with this cmd, and had to wait for the system auto-mount...
thks for your time !

**Comment by syscl** [comment]
@vinceoralim 

please try the new update fixUSB.sh.

wait for your feedback.

syscl

**Comment by syscl** [comment]
@vinceoralim 
What's the timeout error? Can you show me more details since I have not encountered that issue.

syscl

**Comment by vinceoralim** [comment]
thks, the new one doesn't work either the drive is still missing
As I said, the timeout error does not occur any more, once your script is registered.

**Comment by syscl** [comment]
Try reboot and see if the script work.


syscl

**Comment by syscl** [comment]
@vinceoralim 
I'm now fixing it, please wait...

**Comment by vinceoralim** [comment]
great, it seems to work without reboot !
I'll dig into some more experiments and let you know.

thanks for your time and effort !!

**Comment by vinceoralim** [comment]
No issue so far, after several sleep/wake tries ou reboots (you may close this issue) !
thanks again !

**Comment by syscl** [comment]
Lol, I'm glad to see that :)

I rarely close issues. Because I cannot verify whether the issue solve or not, it depends on you(to close it) ;)

Again, I'm very happy to see the fix help your laptop and thx for your important feedback about a real Mac!
Have a good day!
syscl

**Comment by vinceoralim** [comment]
off topic, since you seem to be a hackintosh expert : 
- did you successfully submit an app with xCode from one of these computers ?
- if not, have you heard something about it ?
thks

**Comment by syscl** [comment]
No, I was thinking of doing that, but at this point, I'm busy doing my non-hack related work(startup).

The answer is positive, since software development shows no difference between hackintosh and Macintosh(We can download from Mac App Store like a real Mac, and yes, with our own apple ids). Netease Music, one of the largest music app on Mac App Store, are developed by hackintosh laptop with Xcode. 

There's various contribution/improvements for OS X/iOS by hackintohers including kernel, function fix(just like those under my github.com), softwares... Master Chief, the founder of Revoboot and a famous hacker, was hired by Apple.Inc since 2010(if my memory doesn't get mess).

Wish this could help you.
syscl

**Comment by vinceoralim** [comment]
thank you, very interesting !
As a developper for web/iOS/Android, I decided to switch to real macs when I started, but they are over-rated : poorly equipped, slow, expensive... Ironically, the best thing from Apple is free : OS X

My fear is to face system incompatibilities I have no time or skill to deal with.
But I may reconsider it in the future.

All the best,

Vince

**Comment by syscl** [comment]
@vinceoralim ,
The performance of a real Mac is really a problem! I can buy 2x E5 CPUs with a dual-cores motherboard at the price of MacPro which has limited extension and poor performance at such a price. 

About the slow speed you mention above, try to replace/add SSD for your Mac which will significantly boost your OS X.

The most important thing that prevent me from buying a real MacBook is about freedom. Though, the design of MacBook never fails to fascinate me, I feel uncomfortable when Apple sets various limitation on its hardware. That's why I brought Dell M3800 which has twice the price as rMBP 15', on DELL, I can do whatever I want, such as installing 10.9, 10.10 and 10.11 at the same time w/o any difficulties. And also, since Clover takes the charge of the early booting progress, I can and always bypass some weird limitations from Apple(such as some restriction on SIP).

Back to your worry, if your major/task job is to develop App, OS X on Macs provides the best compatibility. But like learning a new skill, hackintosh will also teach you how to deal with unexpected situations, confront with failures(a must-learn course in hackintosh) and patience. That deserves effort and time. If you have time, it's better to get start with a real Macs to learn hackintosh(your MacBook 2012) which will save you a lot of precious time and you have a way to prevent the worst thing happen.

syscl

**Comment by vinceoralim** [comment]
Performance is not problem for me, my previous mpb 2008 was fair enough.
I did put a SSD, the day I owned my first mac.
SIP is tweakable on real mac in Recovery mode, I did it.

Learning skills is part of our everyday job, and still, 24 hours a day is too short. We have to make choice between amusing ones (I'd like to set up a hackintosh), and efficient ones (make my day).
So far, I need an out of the box computer.
